import "./globals.css";
import { Inter } from "next/font/google";
import { Header } from "../components/Header";
import { ThemeProvider } from "next-themes";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      style={{ scrollBehavior: "smooth" }}
      suppressHydrationWarning
    >
      <body className={inter.className}>
        <ThemeProvider attribute="class">
          <Header />
          <main className="pb-10">{children}</main>
        </ThemeProvider>
      </body>
    </html>
  );
}
